spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:

server:
  servlet:
    session:
      timeout: 6h

logging:
  level:
    root: info
    com.sky: debug
  file:
    name: log/blog-dev.log

mybatis:
  type-aliases-package: com.sky.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


